name: Arduino-lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: arduino/arduino-lint-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          library-manager: update
